markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name:         VERYYOUNG                                         # 博客名称
    description:  I'm veryyoung                                     # 博客描述
    title:        I'm veryyoung                                     # 网页标题
    url:          veryyoung.me                                      # 博客地址
    duoshuo:      veryyoung                                         # 多说ID
    tongji:                                                         # 百度统计ID
    qiniu:                                                          # 七牛云地址
author:
    name:         veryyoung                                         # 作者名称
    email:        veryyoung.me@gmail.com                            # 邮箱地址
    weibo:        http://weibo.com/yangxi0ngwei                     # 微博地址
    github:       https://github.com/veryyoung                      # GitHub地址
    logo:         http://tp3.sinaimg.cn/2536700194/180/5701775994/1 # logo地址
    douban:       
        name:                                                       # 豆瓣地址名称
        key:                                                        # 豆瓣API Key